#!/bin/bash

if [ ! -f data.json ]; then
    echo "data.json not found."
exit 1
fi

name=$(jq -r ".name" data.json | sed 's/.*/\u&/') # capitalize the first letter
formatted_height=$(jq ".height" data.json | awk '{printf "%.1f", $1 / 10}') # convert dm to m
formatted_weight=$(jq '.weight' data.json | awk '{print $1 / 10}') # Convert hectograms to kg
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
